name: Valgrind

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt install dependency
      run: |
        sudo apt-get -y install valgrind
        sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev 
    - name: make test
      run: |
        make test -C Miniproject_01/3_Implementation/
        valgrind ./Miniproject_01/3_Implementation/build/Test_Calender.out
